SELECT * 
FROM PACIENTE
WHERE USUARIO LIKE "CARLOSLOOR";
-- SE MUESTRA LOS ESCPECIALISTAS DISPONIBLES, SU RESENA
SELECT NOMBRE, ESPECIALIDAD
FROM ESPECIALISTA;
-- VER LOS ESPECIALISTAS DISPONLES EN ESE HORARIO 
SELECT E.NOMBRE , ED.HORARIO
FROM ESPECIALISTA E, ESP_DISPONIBLE ED;
-- SE CAMBIA LA DISPONIBILIDAD DE CIERTO HORArio con cierto especialista dispoNIBLE
UPDATE ESP_DISPONIBLE
  SET DISPONIBLE = FALSE 
  WHERE HORARIO = "2021-12-03 12:30:24"; 
 -- MOSTRAR LAS CITAS AGENDADAS 
 SELECT C.FECHA_HORA, E.NOMBRE
 FROM CITA C, ESPECIALISTA E;
 
