-- 1.- SE MUESTRA LOS ESCPECIALISTAS DISPONIBLES, SU RESENA  SI 
CREATE VIEW ESPECIALISTAS_ACTIVOS AS
SELECT NOMBRE,USUARIO_ESP, ESPECIALIDAD,CALIFICACION
FROM ESPECIALISTA;
-- 2.- VER LOS ESPECIALISTAS DISPONLES EN urgencia SI 
CREATE VIEW ESP_URG AS
 SELECT NOMBRE, USUARIO_ESP
 FROM ESPECIALISTA 
 WHERE DISPURG = TRUE ;
  -- 3.- MOSTRAR LAS CITAS AGENDADAS SI 
 CREATE VIEW CITAS_AGENDADAS AS
 SELECT C.FECHA_HORA, E.NOMBRE,C.USUA
 FROM CITA C, ESPECIALISTA E
 WHERE C.USUA_ESP = USUARIO_ESP;